### ISSUE TITLE
Добавить FrameBufferRefDesign в branch fpga/ref_design

### ISSUE THREAD

**Issue by urock** [urock/FpgaOpenCV#2]
- Добавить только исходные файлы и скрипты сборки (как мы любим)
- Создать инстуркцию по сборке
- Создать минимальное readme с описанием проекта и используемых в нем IP ядер 
- Разбораться нужны ли доп лицензии на IP ядра, если нужны, то что делать. Может быть самим написать на HLS, но это крайний случай

**Comment by RostaTasha** [comment]
Необходима лицензия на 5 ядер см. [ссылку](https://github.com/RostaTasha/FpgaOpenCV/tree/fpga/ref_design/fpga/FrameBufferRefDesign)

Есть триальная лицензия на 30 дней на них. На каждое из ядер есть документация, буду разбираться. Проект из  туториала Frame Buffer Design Tutorial успешно собирается. 
Проект представлен в виде сорсов и скриптов сборки, так что никакие дополнительные действия не нужны. Сделала субмодуль на исходный репозиторий, который содержит проект [как работать с субмодулями](https://git-scm.com/book/ru/v1/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9F%D0%BE%D0%B4%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8).

**Comment by urock** [comment]
Проект не собирается на Ubuntu 14.04 Vivado 2015.2 
**не будем с этим разбираться** работать будем в Win7 64

Единственное что, Наташ, плиз проверь, что этот проект может запуститься на машине без лицензий на video ip cores. 

**Без лицензий проект не собирается, пишет следующее:**
embv_python1300c_fb_processing_system7_0  Included   |

----------------------------------------  -----------+
embv_python1300c_fb_v_cfa_0_0             Needs    Purchase   |  
----------------------------------------  -----------+
embv_python1300c_fb_v_cresample_0_0       Design_Lin |  
----------------------------------------  -----------+
embv_python1300c_fb_v_osd_0_0             Design_Lin |  
----------------------------------------  -----------+
embv_python1300c_fb_v_rgb2ycrcb_0_0       Included   |  
----------------------------------------  -----------+
embv_python1300c_fb_v_tc_0_0              Included   |
---------------------------------------  -----------+
embv_python1300c_fb_v_tpg_0_0             Included   |

В итоге только одно ядро вообще не может быть использовано **embv_python1300c_fb_v_cfa_0_0**

![default](https://cloud.githubusercontent.com/assets/1125366/12871853/6ba25a46-cd42-11e5-9316-3ebc2a33c63e.JPG)

**Comment by urock** [comment]
На Windows 7 проект начинает собираться, но ошибка другая - слишком длинные пути. Надо уменьшить внутренние пути в проекте. 

ERROR: [Common 17-680] Path length exceeds 260-Byte maximum allowed by Windows: e:/users/urock/FrameBufferRefDesign/embv_python1300c/Projects/embv_python1300c_fb/MZ7020_EMBV/embv_python1300c_fb.srcs/sources_1/bd/embv_python1300c_fb/ip/embv_python1300c_fb_processing_system7_0_axi_periph_0/embv_python1300c_fb_processing_system7_0_axi_periph_0.xci
